export const SET_ITEMS='SET_ITEMS';
export const SET_INITIAL_STATE='SET_INITIAL_STATE';
export const FILTER_ITEMS='FILTER_ITEMS';
export const SET_SELECTED_ITEM_VALUE = 'SET_SELECTED_ITEM_VALUE';
export const SET_DROPDOWN_STATUS = 'SET_DROPDOWN_STATUS';
export const SET_ERROR='SET_ERROR';
export const SET_MULTI_SELECTED_ITEM = 'SET_MULTI_SELECTED_ITEM';
export const SET_DISABLED = 'SET_DISABLED';
